# This file was generated by Foundry release automation. DO NOT EDIT.
cask "foundry@alpha" do
  version "0.1.0-alpha.16"

  name "Foundry"
  desc "Game engine and editor with Foundry Script"
  homepage "https://github.com/cafecito-games/Foundry"

  livecheck do
    skip "Auto-generated on release."
  end

  conflicts_with cask: ["foundry", "foundry@beta", "foundry@rc"]

  on_macos do
    sha256 "06d8e9808d01eb2db727b8ea7196c8128bf5509a36ac41753133ce52b7939a5a"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_macos.universal.zip"

    app "Foundry.app"
    binary "#{appdir}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"
  end

  on_linux do
    sha256 "b0e21d1f9b0888b6b9e1a2d9e533529d687b1de29d8429053457a0e915116e03"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_linux.x86_64.zip"

    binary "foundry.linuxbsd.editor.x86_64", target: "foundry"
  end

end
