# This file was generated by GoReleaser. DO NOT EDIT.
cask "foundry-tools" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "7ee1bd1dc5f7c72107130a81cc8b8e6524afec5c01a79b0f1bf26d8d475f7f15"
      url "https://github.com/cafecito-games/Foundry-Tools/releases/download/v#{version}/foundry-tools_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13493cf5a0d383c183dbfc4e28deaf04a43ae2a6d08214311779fb8bc37b4a38"
      url "https://github.com/cafecito-games/Foundry-Tools/releases/download/v#{version}/foundry-tools_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19877b4f815a15e11a89850e740c83eda194cff61517809eb1507a956847c6b1"
      url "https://github.com/cafecito-games/Foundry-Tools/releases/download/v#{version}/foundry-tools_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ab6e61eb27cfd97d4755cfe5d27035b2e64bdd7585be015e0985d7ec301c1f4"
      url "https://github.com/cafecito-games/Foundry-Tools/releases/download/v#{version}/foundry-tools_#{version}_linux_arm64.tar.gz"
    end
  end

  name "foundry-tools"
  desc "Foundry Engine development tools"
  homepage "https://github.com/cafecito-games/foundry-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anvil"
  binary "protoc-gen-foundryscript"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anvil"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-foundryscript"]
    end
  end

  # No zap stanza required

end
