# This file was generated by Foundry release automation. DO NOT EDIT.
cask "foundry@alpha" do
  version "0.1.0-alpha.7"

  name "Foundry"
  desc "Game engine and editor with Foundry Script"
  homepage "https://github.com/cafecito-games/Foundry"

  livecheck do
    skip "Auto-generated on release."
  end

  conflicts_with cask: ["foundry", "foundry@beta", "foundry@rc"]

  on_macos do
    sha256 "ea501a4802cd43edbf48d1bc6524b0c8ea28df306430fbdc4268bcb507e2d6e2"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_macos.universal.zip"

    app "Foundry.app"
    binary "#{appdir}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"
  end

  on_linux do
    sha256 "2b7df14c469cb820db76980e07bed81ea0f51914310653e791102ec901415b65"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_linux.x86_64.zip"

    binary "foundry.linuxbsd.editor.x86_64", target: "foundry"
  end

end
