# This file was generated by Foundry release automation. DO NOT EDIT.
cask "foundry@alpha" do
  version "0.1.0-alpha.5"

  name "Foundry"
  desc "Game engine and editor with Foundry Script"
  homepage "https://github.com/cafecito-games/Foundry"

  livecheck do
    skip "Auto-generated on release."
  end

  conflicts_with cask: ["foundry", "foundry@beta", "foundry@rc"]

  on_macos do
    sha256 "9f785eea7ac48aa17eba6d419064e10f9e8b345234afa26414600b9cbc4fa16b"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_macos.universal.zip"

    app "Foundry.app"
    binary "#{appdir}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"
  end

  on_linux do
    sha256 "2a7006c9e6753cb04d3e27bc10a9e70ca08453a6a22877991742aeec94106954"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_linux.x86_64.zip"

    binary "foundry.linuxbsd.editor.x86_64", target: "foundry"
  end

end
