# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdkit" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gdkit"]
      end
    end
  end

  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "a422a9f5e1f12fda443c7d48fd77e0d4231a205f49e660676279f3d0c2c9b020"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "54ab45a7bfcbf08872fd302f0810dd0782916740cc6e2fdb90d4d90491dad564"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c332d91e8cfe1b46e920fda9321bca97ef7c47000ba06a23e9711e0774c69401"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "91a95277f30c05ac7d42b2cef723e6f462acc46cd138dbedf3f3b20e08d85f88"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gdkit"
  desc "Static-analysis toolkit for Godot 4 GDScript"
  homepage "https://github.com/cafecito-games/gdkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdkit"

  # No zap stanza required
end
