# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdkit" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gdkit"]
      end
    end
  end

  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "2fcf73a15bb3437aa6706c1138b3b739f8d70cd162e9b3c6465c752c1c566c17"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c5700fd614626f6a540a90cdfb69db74b238ec38748fb829badb34b7bd4058e"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f683d4c4d28697d45e883ed023ab24885c4d8896c5a8d1e3193f5d73a011b9da"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "71a91aca2d96f7bf36a38e889bb431ec09c72955196b83793b29705f34565031"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gdkit"
  desc "Static-analysis toolkit for Godot 4 GDScript"
  homepage "https://github.com/cafecito-games/gdkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdkit"

  # No zap stanza required
end
