# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdkit" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gdkit"]
      end
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "71b34968fa6a5a93e1acda150d38d99ca2291679f21f4c978bd251c3cd87f7f2"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3990b0ae0170d8a3cf42638bc84e3b57fecf4ca4da30f695fa464c6d84dc457c"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "feb4b7ee0f060a6479011e6f56275a924bee13705f16faef82c2fb226c2ea4ce"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2641e241d48514dd4188450cb42c7903150cba807f988a8b7ccb841420fc597"
      url "https://github.com/cafecito-games/gdkit/releases/download/v#{version}/gdkit_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gdkit"
  desc "Static-analysis toolkit for Godot 4 GDScript"
  homepage "https://github.com/cafecito-games/gdkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdkit"

  # No zap stanza required
end
