# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdparser" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "7419f48e85047ea0f544bfc5566974776ba7aed864f5c2bc8fae2ad3942c2b99"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc515b91939221c4884dad7d9cb8b0e3cee3d471bbd4c1ed47bff2e946d7da72"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "da2fe3ee22f4e6e0089e651f6d0853cfb72acc688150a9c770437a88402d2e2c"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11098b17b1a7c3585e9e994e5f196537688f78c8c12c45687a6ae717f7085011"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gdparser"
  desc "Parser and canonical formatter for Godot 4 source and text formats"
  homepage "https://github.com/cafecito-games/gdparser"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdparser"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdparser"]
    end
  end

  # No zap stanza required
end
