# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdparser" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e289f45a89ed9a7daa6eac3b6c8e637430d033610e631c3978ddaf5cd2f81ec3"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "212c4171176e446905573023e25b6f860c23ce49cb068dbd6be6709b9739a4be"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e622b54596f762e3f9825f4801d072743a8678278e15c33f899868742512bd02"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5b6363e5303d1885bf325e39c681ecd8bf9c8f901a517ef88e5047abbb6eeee3"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gdparser"
  desc "Parser and canonical formatter for Godot 4 source and text formats"
  homepage "https://github.com/cafecito-games/gdparser"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdparser"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdparser"]
    end
  end

  # No zap stanza required
end
