# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdparser" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gdparser"]
      end
    end
  end

  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "1b69495ae83381d70ca92a50fdc5f95fd5e999f3e6f3d07c0a9e9aa68f328aa0"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3933a830d81e69824efe998ebac4470ded01b65519fe234453097622005cbfca"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a16e71469ad9b169d80f7cede68327c2675caba3794c42fa94aad6fb05e53e8d"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a35b12924ef7726566af512755e5474464fa0f31220ac8b318023e778bc5dfae"
      url "https://github.com/cafecito-games/gdparser/releases/download/v#{version}/gdparser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gdparser"
  desc "Parser and canonical formatter for Godot 4 source and text formats"
  homepage "https://github.com/cafecito-games/gdparser"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdparser"

  # No zap stanza required
end
