# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdproto" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "235dbd369951aae4c18136952ddfafdd062a6b4e0059354ec0050f6b0ece28b4"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "11e1ea079dcd386c85eedc37128be14d41f070f5bdd01cb4d6201bf1187c8927"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ae8eef36d44bf0d3a87871c9130be6463fe4c7bf49174379b5632fb17798fea"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "624de7affafb4fe80f703970153515ce78bbef57c508a45702ec99c20f6b8214"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gdproto"
  desc "Protocol Buffers v3 to GDScript (Godot 4.6+) compiler"
  homepage "https://github.com/cafecito-games/gdproto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdproto"
  binary "protoc-gen-gdscript"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdproto"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-gdscript"]
    end
  end

  # No zap stanza required

end
