# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdproto" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "ac83a72f3f55fd84303d0d30c77d3238baef4fce30b18652e0183a471353cd21"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "10f7e3fe2ea7ab1457200febfac83f48285fa83b95fe46908abbcfc965717b91"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "306da0daf9105b11cffe0b60914b59a32e5783102aae261112b665511ebb1e9e"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9621777307fa78a86820f61d8ba9668ce77b14665b2bb53f4233def39858b614"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gdproto"
  desc "Protocol Buffers v3 to GDScript (Godot 4.6+) compiler"
  homepage "https://github.com/cafecito-games/gdproto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdproto"
  binary "protoc-gen-gdscript"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdproto"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-gdscript"]
    end
  end

  # No zap stanza required

end
