# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdproto" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "c66d67d0fc9bcdb7d947c47c4ae2e86f1085b9af4a36024c9e4e015b7e4fd8c7"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6aab99afc5f2ae7e4c6d4501e1923bbe8cfa5324c656408ef52a37a11767c066"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "36dda5ba5af24009abe7ff5013c507900e0e5e49278603c17bc7407ada6e083b"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9684b4f51ce3f068c8bbff8cf806405fff55fa7b5979c0481d0104c5cb769dc"
      url "https://github.com/cafecito-games/gdproto/releases/download/v#{version}/gdproto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gdproto"
  desc "Protocol Buffers v3 to GDScript (Godot 4.6+) compiler"
  homepage "https://github.com/cafecito-games/gdproto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdproto"
  binary "protoc-gen-gdscript"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdproto"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-gdscript"]
    end
  end

  # No zap stanza required

end
