# This file was generated by GoReleaser. DO NOT EDIT.
cask "gpm" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "59fcb4578a4ee19460a2e38c8729db812d841d44e9f75456688d1cb88cc397f4"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "faed011f6793f0bac2ace22d970c1d48a82169dc1ac3cf383536804f1233d03e"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "397c69d74e36513c88fd315316862979d3eb07f6c4661133024c7b209fb0fd2a"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "54facfe0b28b59a6c63b42d7474be491ffbfb89447a51bdc0989e1e932cbc7c5"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gpm"
  desc "CLI addon manager for Godot projects"
  homepage "https://github.com/cafecito-games/godot-package-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gpm"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gpm"]
    end
  end

  # No zap stanza required

end
