# This file was generated by GoReleaser. DO NOT EDIT.
cask "gpm" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9d7b21b3258157657909884536336295b51e5725737d2325619ea7e63b981d30"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e85ff151de95dd650263008d1147ef09b03cb205f984558b62240e3cfd1e707f"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e11e2cb75f10a06afe4caf60dd4b3a3fc196e94f06dfebeaf8397ed7fd0b1131"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8bdb402b37b07adde51bb3d59fa24e9e8c3bceab0307b2a4038f477fc259b10e"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gpm"
  desc "CLI addon manager for Godot projects"
  homepage "https://github.com/cafecito-games/godot-package-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gpm"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gpm"]
    end
  end

  # No zap stanza required

end
