# This file was generated by GoReleaser. DO NOT EDIT.
cask "gpm" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gpm"]
      end
    end
  end

  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "8ffabb157b18fb11483f4e1c209ab171a6172313cfd0e6358e5d3ff4f2416cdc"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "566a8e85ac7891339fe3f812c29b6c87b93ce80ab0bfb420b35b18cd68c1a59b"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb807f6326bf038cf7b2b23f80ef43724196eecb8cecd507e8b55019a448948a"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "beaba7bc7aa2d05dba09989530fda8240ca53ce2202a63c58f682a8de3527299"
      url "https://github.com/cafecito-games/godot-package-manager/releases/download/v#{version}/gpm_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gpm"
  desc "CLI addon manager for Godot projects"
  homepage "https://github.com/cafecito-games/godot-package-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gpm"

  # No zap stanza required
end
