# This file was generated by GoReleaser. DO NOT EDIT.
cask "grafo" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/grafo"]
      end
    end
  end

  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "3ceb6da1b8e92a0baace85f90547cc19b5d5ff1649cbe0e2d56e7364124cf292"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6495a39927724b9167c5b1f1064ab7cf22cfe2ebedaa80d40d6656615e1392cc"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1672519e4374f22b5b920cb61959bb03d1c8196091a8034b5b604e8f9fa06fc1"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "641a4ace88f44ca336a82c139393676daf343f6d1b6959171173b55c96293444"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "grafo"
  desc "Code graph indexer and query CLI for agent-assisted development"
  homepage "https://github.com/cafecito-games/grafo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grafo"

  # No zap stanza required
end
