# This file was generated by GoReleaser. DO NOT EDIT.
cask "grafo" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/grafo"]
      end
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "1e230a23c10531a7cfc2af78b36c7666b0af5dc5a864626b04ba1de2e3dc56b0"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5fd19b4ab5d9bba14ee59ee022713a97a9e2d32befe1368bb40deacca2103548"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "55f60be428d156a1caef53aecdea3add706f996accd084856db8ed5a2e432142"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa7cbe5bfbd4c4db337a3c8f880730552b9b29ab6d5956854d93921e2334db5a"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "grafo"
  desc "Code graph indexer and query CLI for agent-assisted development"
  homepage "https://github.com/cafecito-games/grafo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grafo"

  # No zap stanza required
end
