# This file was generated by GoReleaser. DO NOT EDIT.
cask "grafo" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/grafo"]
      end
    end
  end

  version "0.2.7"

  on_macos do
    on_arm do
      sha256 "8b1a69e9d1c70ea8965e9072a4461cac87281acc054709d63cf64b4ae4e95b8d"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e441011c7447610d340380fbae896a7f27638fc8b42e1174091237d19b85e9f9"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a2caeeb3599d4549ced95fa85cfdfc275ab05f8cb3eb0742f8f0457f6c6177e2"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "03e4c33a242d544f07e0c154fbf7e4fc98137c941a9880ff7dd19ae0d23190d2"
      url "https://github.com/cafecito-games/grafo/releases/download/v#{version}/grafo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "grafo"
  desc "Code graph indexer and query CLI for agent-assisted development"
  homepage "https://github.com/cafecito-games/grafo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grafo"

  # No zap stanza required
end
